services:
  - type: web
    name: ventas
    env: python
    region: oregon  # o singapore para Latinoam√©rica
    plan: free
    buildCommand: |
      pip install -r requirements.txt
    startCommand: python odoo-bin -c odoo.conf
    envVars:
      - key: dpg-d60g5uvpm1nc73crkpt0-a
        fromDatabase:
          name: venta_pdmw
          property: connectionString
      - key: ADDONS_PATH
        value: addons,custom_addons

